number_of_variations: 2
layer_order:
  - name: "Background"
    blend: 'overlay'
    opacity: 1
  - name: "Eyeball"
  - name: "Eye color"
  - name: "Iris"
  - name: "Shine"
  - name: "Bottom lid"
  - name: "Top lid"